name: Build docs
on: [push]
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: vuepress-deploy
              uses: jenkey2011/vuepress-deploy@master
              env:
                  ACCESS_TOKEN: ${{ secrets.VUEPRESS_TOKEN }}
                  TARGET_REPO: constantinmaes/node-opening-hours
                  TARGET_BRANCH: main
                  BUILD_SCRIPT: yarn && yarn docs:build
                  BUILD_DIR: docs/.vuepress/dist
