name: Publish Package to npmjs
on: workflow_dispatch
jobs:
  call-workflow-2-in-local-repo:
    uses: ./.github/workflows/build.yml
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: node-opening-hours-${{ github.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
